/*
 * File: app/view/RcSteeringPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RcTRex.view.RcSteeringPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.rcsteeringpanel',

    requires: [
        'RcTRex.view.RcSteeringPanelViewModel',
        'Ext.field.Slider',
        'Ext.field.Number',
        'Ext.Button',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line'
    ],

    viewModel: {
        type: 'rcsteeringpanel'
    },
    fullscreen: true,
    title: 'RC Steering Tester',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            itemId: 'steering',
            items: [
                {
                    xtype: 'container',
                    userCls: 'steering-label',
                    margin: 5,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Left',
                            margin: '0 0 0 60'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: 'Right'
                        }
                    ]
                },
                {
                    xtype: 'sliderfield',
                    bind: '{steeringSetValue}',
                    itemId: 'steeringSetPointSlider',
                    name: 'steeringSlider',
                    margin: '0 10 5 10',
                    label: 'Steer',
                    labelWidth: 65,
                    value: 500,
                    liveUpdate: true,
                    maxValue: 1000
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'throttle',
            items: [
                {
                    xtype: 'container',
                    userCls: 'steering-label',
                    margin: 5,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Reverse',
                            margin: '0 0 0 60'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: 'Forward'
                        }
                    ]
                },
                {
                    xtype: 'sliderfield',
                    bind: '{throttleSetValue}',
                    itemId: 'throttleSlider',
                    name: 'throttleSlider',
                    margin: '0 10 5 10',
                    label: 'Throttle',
                    labelWidth: 65,
                    value: 50,
                    liveUpdate: true,
                    maxValue: 1000
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 't-rex pan',
            items: [
                {
                    xtype: 'container',
                    userCls: 'steering-label',
                    margin: 5,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Left',
                            margin: '0 0 0 60'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: 'Right'
                        }
                    ]
                },
                {
                    xtype: 'sliderfield',
                    bind: '{trexPanSetValue}',
                    itemId: 'trexPanSlider',
                    name: 'trexPanSlider',
                    margin: '0 10 5 10',
                    label: 'T-Rex Pan',
                    labelWidth: 68,
                    value: 500,
                    liveUpdate: true,
                    maxValue: 1000,
                    listeners: {
                        change: 'onTrexPanSliderChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 't-rex tilt',
            items: [
                {
                    xtype: 'container',
                    userCls: 'steering-label',
                    margin: 5,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Down',
                            margin: '0 0 0 60'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: 'Up'
                        }
                    ]
                },
                {
                    xtype: 'sliderfield',
                    bind: '{trexTiltSetValue}',
                    itemId: 'trexTiltSlider',
                    name: 'trexTiltSlider',
                    margin: '0 10 5 10',
                    label: 'T-Rex Tilt',
                    labelWidth: 65,
                    value: 500,
                    liveUpdate: true,
                    maxValue: 1000,
                    listeners: {
                        change: 'onTrexTiltSliderChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 't-rex jaw',
            items: [
                {
                    xtype: 'container',
                    userCls: 'steering-label',
                    margin: 5,
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'container',
                            html: 'Close',
                            margin: '0 0 0 60'
                        },
                        {
                            xtype: 'container',
                            flex: 1
                        },
                        {
                            xtype: 'container',
                            html: 'Open'
                        }
                    ]
                },
                {
                    xtype: 'sliderfield',
                    bind: '{trexJawSetValue}',
                    itemId: 'trexJawSlider',
                    name: 'trexJawSlider',
                    margin: '0 10 5 10',
                    label: 'T-Rex Jaw',
                    labelWidth: 65,
                    value: 0,
                    liveUpdate: true,
                    maxValue: 1000,
                    listeners: {
                        change: 'onTrexJawSliderChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'hbox',
            layout: 'hbox',
            items: [
                {
                    xtype: 'container',
                    itemId: 'ThrottleHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'throttleLabel',
                            html: 'Throttle',
                            margin: 10
                        },
                        {
                            xtype: 'numberfield',
                            bind: '{throttleSetValue}',
                            itemId: 'throttleText',
                            width: 100,
                            margin: 10,
                            label: 'set',
                            labelWidth: 35,
                            value: 0,
                            clearable: false,
                            maxValue: 1000,
                            minValue: 0,
                            listeners: {
                                change: 'onThrottleTextChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'setPointHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'setPointActualLabel',
                            html: 'Steer Set & Actual',
                            margin: 10
                        },
                        {
                            xtype: 'numberfield',
                            bind: '{steeringSetValue}',
                            itemId: 'steeringSetPointText',
                            width: 120,
                            margin: 10,
                            label: 'set point',
                            labelWidth: 70,
                            value: 50,
                            clearable: false,
                            maxValue: 1000,
                            minValue: 0,
                            listeners: {
                                change: 'onSteeringSetPointTextChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'steeringCurrent',
                            width: 120,
                            margin: 10,
                            label: 'current',
                            labelWidth: 70,
                            value: 0,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'pidError',
                            width: 120,
                            margin: 10,
                            label: 'error',
                            labelWidth: 70,
                            value: 0,
                            clearable: false
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'steeringCurrentAdc',
                            width: 120,
                            margin: 10,
                            label: 'adc value',
                            labelWidth: 70,
                            value: 0,
                            clearable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'pidHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'pidVariablesLabel',
                            html: 'PID Constants',
                            margin: 10
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'pidConstantP',
                            width: 80,
                            margin: 10,
                            label: 'P',
                            labelWidth: 25,
                            value: 0,
                            clearable: false,
                            decimals: 3
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'pidConstantI',
                            width: 80,
                            margin: 10,
                            label: 'I',
                            labelWidth: 25,
                            value: 0,
                            clearable: false,
                            decimals: 3
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'pidConstantD',
                            width: 80,
                            margin: '10 10 0 10',
                            label: 'D',
                            labelWidth: 25,
                            value: 0,
                            clearable: false,
                            decimals: 3
                        },
                        {
                            xtype: 'button',
                            itemId: 'updatePidConstants',
                            margin: '10 10 10 30',
                            text: 'Update',
                            listeners: {
                                tap: 'onMybutton1Tap'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'buttonsHbox',
                    userCls: 'variable-box',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'buttonsLabel',
                            html: 'Control',
                            margin: 10
                        },
                        {
                            xtype: 'button',
                            margin: '0 20 5 20',
                            text: 'Stop Steering',
                            listeners: {
                                tap: 'onMybuttonTap'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '5 20 5 20',
                            text: 'Stop Throttle',
                            listeners: {
                                tap: 'onMybuttonTap2'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '5 20 5 20',
                            text: 'Stop Steer Loop',
                            listeners: {
                                tap: 'onMybuttonTap1'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '5 20 5 20',
                            text: 'Start Steer Loop',
                            listeners: {
                                tap: 'onMybuttonTap11'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'gamepadHbox',
                    userCls: 'variable-box',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'gamepadLabel',
                            html: 'Gamepad',
                            margin: 10
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'gamepadRightLeft',
                            width: 120,
                            margin: 10,
                            label: 'R / L',
                            labelWidth: 40,
                            clearable: false,
                            maxValue: 100,
                            minValue: -2
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'gamepadFwd',
                            width: 120,
                            margin: 10,
                            label: 'Fwd',
                            labelWidth: 40,
                            clearable: false,
                            maxValue: 100,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            itemId: 'gamepadRev',
                            width: 120,
                            margin: 10,
                            label: 'Rev',
                            labelWidth: 40,
                            clearable: false,
                            maxValue: 100,
                            minValue: 0
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'buttonsHbox1',
                    userCls: 'variable-box',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'soundButtonsLabel',
                            html: 'Sounds',
                            margin: 10
                        },
                        {
                            xtype: 'button',
                            margin: '0 20 5 20',
                            text: 'X: T Rex',
                            listeners: {
                                tap: 'onMybuttonTap3'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: '5 20 5 20',
                            text: 'Y: Next Sound',
                            listeners: {
                                tap: 'onMybuttonTap21'
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'serialCommandHbox',
                    userCls: 'variable-box',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            itemId: 'serialCommandsLabel',
                            html: 'Arduino Command',
                            margin: 10
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'arduinoCommand',
                            width: 120,
                            margin: 10,
                            clearable: false
                        },
                        {
                            xtype: 'button',
                            margin: '0 20 5 20',
                            text: 'Send',
                            listeners: {
                                tap: 'onMybuttonTap31'
                            }
                        },
                        {
                            xtype: 'container',
                            html: '<u>LEDS:</u><BR>1-4 solid colors<BR>5-8 blik<BR><u>Text</u><BR>t1Hello World<BR>&nbsp;&nbsp;&nbsp;on line 1 show Hello World'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'debugOutputLabel',
            html: 'Debug Output',
            margin: 10
        },
        {
            xtype: 'cartesian',
            height: 250,
            hidden: false,
            itemId: 'steeringChart',
            animation: false,
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            bind: {
                store: '{steeringChartStore}'
            },
            axes: [
                {
                    type: 'numeric',
                    grid: {
                        odd: {
                            fill: '#e8e8e8'
                        }
                    },
                    maximum: 1100,
                    minimum: -100,
                    position: 'left',
                    title: 'Position'
                }
            ],
            series: [
                {
                    type: 'line',
                    colors: [
                        'rgba(200,0,0,0.3)'
                    ],
                    style: {
                        stroke: 'rgb(200,0,0)',
                        step: true
                    },
                    xField: 'x',
                    yField: 'steeringCurrent'
                },
                {
                    type: 'line',
                    colors: [
                        'rgba(0,200,0,0.3)'
                    ],
                    style: {
                        stroke: 'rgb(0,200,0)',
                        step: true
                    },
                    xField: 'x',
                    yField: 'steeringTargetPoint'
                }
            ]
        },
        {
            xtype: 'container',
            height: 240,
            itemId: 'debugOutputContainerOuter',
            userCls: 'debugOutputContainer',
            margin: 10,
            scrollable: 'vertical',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    itemId: 'debugOutputContainer'
                }
            ]
        }
    ],
    listeners: {
        painted: 'onFormpanelPainted'
    },

    onTrexPanSliderChange: function(me, newValue, oldValue, eOpts) {
        this.socketSend(Ext.encode({
            action:'updateTrexPan',
            value:this.getArrayFirstValue(newValue)
        }));
    },

    onTrexTiltSliderChange: function(me, newValue, oldValue, eOpts) {
        this.socketSend(Ext.encode({
            action:'updateTrexTilt',
            value:this.getArrayFirstValue(newValue)
        }));
    },

    onTrexJawSliderChange: function(me, newValue, oldValue, eOpts) {
        this.socketSend(Ext.encode({
            action:'updateTrexJaw',
            value:this.getArrayFirstValue(newValue)
        }));
    },

    onThrottleTextChange: function(field, newValue, oldValue, eOpts) {
        this.socketSend(Ext.encode({
            action:'updateThrottle',
            value:this.getArrayFirstValue(newValue)
        }));
    },

    onSteeringSetPointTextChange: function(field, newValue, oldValue, eOpts) {
        newValue = this.getArrayFirstValue(newValue);

        if(!this.lastSteeringChangeDefered){
            this.lastSteeringChangeDefered = true;

            if(this.lastSent != newValue){
                this.sendUpdateSteering(newValue);
                this.lastSent = newValue;
            }
            Ext.defer(function(){
                this.lastSteeringChangeDefered = false;
                var currentValue = field.getValue();
                if(currentValue && currentValue.constructor === Array){
                    currentValue = currentValue[0];
                }
                if(this.lastSent != currentValue){
                    this.lastSent = currentValue;
                    this.sendUpdateSteering(currentValue);
                }
            },2,this);
        }
    },

    onMybutton1Tap: function(button, e, eOpts) {
        var p = this.queryById('pidConstantP').getValue(),
            i = this.queryById('pidConstantI').getValue(),
            d = this.queryById('pidConstantD').getValue();

        if(p === null || i === null || d === null){
            Ext.Msg.alert(' ','Invalid Constants! Please try again!');
            return false;
        }
        this.socketSend(Ext.encode({
            action:'updatePidConstants',
            p: p,
            i: i,
            d: d
        }));
    },

    onMybuttonTap: function(button, e, eOpts) {
        this.stopSteeringMovement();
    },

    onMybuttonTap2: function(button, e, eOpts) {
        this.socketSend(Ext.encode({
            action:'stopThrottle'
        }));
    },

    onMybuttonTap1: function(button, e, eOpts) {
        this.socketSend(Ext.encode({
            action:'stopSteeringControlLoop'
        }));
    },

    onMybuttonTap11: function(button, e, eOpts) {
        this.socketSend(Ext.encode({
            action:'startSteeringControlLoop'
        }));
    },

    onMybuttonTap3: function(button, e, eOpts) {
        this.trexscream();
    },

    onMybuttonTap21: function(button, e, eOpts) {
        this.playnextsound();
    },

    onMybuttonTap31: function(button, e, eOpts) {
        var arduinoCommand = this.queryById('arduinoCommand');

        var command = arduinoCommand.getValue();
        if(command == ''){
            Ext.Msg.alert(' ','Please enter an Arduino Command');
            return;
        }

        this.socketSend(Ext.encode({
            action:'arduinoCommand',
            command:command
        }));

    },

    onFormpanelPainted: function(sender, element, eOpts) {
        this.websocketInit();
        this.gamepadInit();


        this.trexPanSlider = this.queryById('trexPanSlider');
        this.trexTiltSlider = this.queryById('trexTiltSlider');

        this.fieldGamepadLeftRight = this.queryById('gamepadRightLeft');
        this.fieldGamepadFwd = this.queryById('gamepadFwd');
        this.fieldGamepadRev = this.queryById('gamepadRev');

        this.fieldSteeringSetPointText = this.queryById('steeringSetPointText');
        this.fieldThrottleText = this.queryById('throttleText');

        this.fieldSteeringCurrent = this.queryById('steeringCurrent');
        this.fieldPidError = this.queryById('pidError');
        this.fieldSteeringCurrentAdc = this.queryById('steeringCurrentAdc');

        this.wsPanLast = 0;
        this.wsTiltLast = 0;
        this.wsThrottleLast = 0;

        this.gamePadPanLast = 500;
        this.gamePadTiltLast = 500;
    },

    trexscream: function() {
        this.socketSend(Ext.encode({
            action:'trexscream'
        }));
    },

    getArrayFirstValue: function(value) {
        if(value && value.constructor === Array){
            return value[0];
        }
        return value;
    },

    cycleEyeColor: function() {
        this.socketSend(Ext.encode({
            action:'cycleeyecolor'
        }));
    },

    playnextsound: function() {
        this.socketSend(Ext.encode({
            action:'playnextsound'
        }));
    },

    websocketInit: function() {
        	this.socket = new WebSocket('ws://'+window.location.host+'/wsapi');

            this.recievedMessages = 0;
            this.chartedMessages = 0;

            this.chartArray = [];
            this.chartStore = this.lookupViewModel().getStore('steeringChartStore');
            this.steeringChart = this.queryById('steeringChart');

            this.appendDebugOutput("Opening Websocket");

        	this.socket.onerror = (function(){
        		this.appendDebugOutput("error with websocket!");
                this.socket = false;
        	}).bind(this);
        	this.socket.onclose = (function(){
        		this.appendDebugOutput("websocket closed!");
                this.socket = false;
        	}).bind(this);

        	this.socket.onmessage = this.socketReceive.bind(this);


        	this.socket.onopen = (function(){
                this.socketSend(Ext.encode({
                    action:'getPidConstants'
                }));
        	}).bind(this);
    },

    socketSend: function(message) {
        if(!this.socket){
            console.log('Websocket not started or failed');
            return false;
        }

        if(this.socket.readyState !== WebSocket.OPEN){
            console.log('Websocket not connected');
            return false;
        }

        this.socket.send(message);
    },

    stopSteeringMovement: function() {
        this.socketSend(Ext.encode({
            action:'stopSteeringMovement'
        }));
    },

    socketReceive: function(message) {
        // console.log('recieved message');
        // console.log(message.data);
        //this.appendDebugOutput('recieved message: '+message.data);


        var jsonData = JSON.parse(message.data);

        if(!jsonData.msgType){
            console.log('Missing msgType!');
            console.log(jsonData);
            return false;
        }
        switch(jsonData.msgType){
            default:
                console.log('Invalid msgType!');
                console.log(jsonData);
                break;
            case 'status':
                this.msgUpdateStatus(jsonData);
                break;
            case 'pidConstants':
                this.msgUpdatePidConstants(jsonData);
                break;
        }


    },

    sendUpdateSteering: function(value) {
        this.socketSend(Ext.encode({
            action:'updateSteering',
            value:value
        }));
    },

    msgUpdateStatus: function(jsonData) {
        // this.recievedMessages++;
        this.chartedMessages++;


        // if(this.recievedMessages > 100){
        //     this.recievedMessages = 0;
        //     this.clearDebugOutput();
        //     //chartStore.removeAll();
        // }



        if(this.chartStore.count() > 100){
            this.chartStore.removeAt(0,1);
        }

        //this.steeringChart.suspendAnimation();
        // if(this.chartArray.length > 100){
        //     this.chartArray.shift();
        // }
        // this.chartArray.push([this.chartedMessages, jsonData.steeringCurrent, jsonData.steeringTargetPoint]);

        // this.chartStore.loadData(this.chartArray);

        this.chartStore.loadData([[this.chartedMessages, jsonData.steeringCurrent, jsonData.steeringTarget]], true);

        //this.steeringChart.resumeAnimation();

        this.fieldSteeringCurrent.setValue(jsonData.steeringCurrent);
        this.fieldPidError .setValue(jsonData.pidError);
        this.fieldSteeringCurrentAdc.setValue(jsonData.steeringCurrentAdc);

    },

    msgUpdatePidConstants: function(jsonData) {
        this.queryById('pidConstantP').setValue(jsonData.p);
        this.queryById('pidConstantI').setValue(jsonData.i);
        this.queryById('pidConstantD').setValue(jsonData.d);
    },

    gamepadInit: function() {
        window.addEventListener("gamepadconnected", this.gamepadConnected.bind(this));
        window.addEventListener("gamepaddisconnected", this.gamepadDisconnected.bind(this));

    },

    gamepadConnected: function(e) {
        console.log("gamepad connected");
        console.log(e);

        this.appendDebugOutput("Gamepad connected at index "+e.gamepad.index+", id "+e.gamepad.id+". "+e.gamepad.buttons.length+" buttons, "+e.gamepad.axes.length+" axes");


        if(e.gamepad.id.indexOf('Xbox') !== -1){
            this.gamepadBeginLoop(e.gamepad);
        }else{
            this.appendDebugOutput("Not an xbox controller. Skipping!");
        }
    },

    gamepadDisconnected: function(e) {

            console.log("gamepad disconnected");
            console.log(e);

            this.appendDebugOutput("Gamepad disconnected at index "+e.gamepad.index+", id "+e.gamepad.id);

            clearInterval(this.gamePadLoops[e.gamepad.id]['loop'])
    },

    gamepadBeginLoop: function(gamepad) {
        if(!this.gamePadLoops){
            this.gamePadLoops = {};
        }

        // if(this.gamePadLoops[gamepad.id]){
        //     return;
        // }
        this.gamePadLoops[gamepad.id] = {
            gamepad:gamepad
        };

        this.gamePadLoops[gamepad.id]['loop'] = setInterval(this.gamepadUpdate.bind(this), 50, gamepad);

    },

    gamepadUpdate: function(gamepad) {
        //console.log('gamepadUpdate');

        var gamepadUpdate = navigator.getGamepads();

        if(gamepadUpdate[gamepad.index]){
            gamepad = gamepadUpdate[gamepad.index];
        }else{
            console.log('gamepad no longer available?');
            cancelInterval(this.gamePadLoops[e.gamepad.id]['loop']);
            return;
        }
        //console.log(gamepad);

        //console.log('Fwd: '+gamepad.buttons[7].value);
        //console.log('Rev: '+gamepad.buttons[6].value);

        //console.log('Right: '+gamepad.axes[2]);


        //D Pad
        // 12 Up
        // 13 Down
        // 14 Left
        // 15 Right
        var incrementValue = 20;
        var newValue;
        if(gamepad.buttons[12].value == 1 && this.buttonDupLastValue != gamepad.buttons[12].value){
            newValue = this.getArrayFirstValue(this.trexTiltSlider.getValue()) + incrementValue;
            //console.log('new tilt ',newValue);
            this.trexTiltSlider.setValue(newValue);
        }
        this.buttonDupLastValue = gamepad.buttons[12].value;

        if(gamepad.buttons[13].value == 1 && this.buttonDdownLastValue != gamepad.buttons[13].value){
            newValue = this.getArrayFirstValue(this.trexTiltSlider.getValue()) - incrementValue;
            //console.log('new tilt ',newValue);
            this.trexTiltSlider.setValue(newValue);
        }
        this.buttonDdownLastValue = gamepad.buttons[13].value;

        if(gamepad.buttons[14].value == 1 && this.buttonDleftLastValue != gamepad.buttons[14].value){
            newValue = this.getArrayFirstValue(this.trexPanSlider.getValue()) + incrementValue;
            //console.log('new pan ',newValue);
            this.trexPanSlider.setValue(newValue);
        }
        this.buttonDleftLastValue = gamepad.buttons[14].value;

        if(gamepad.buttons[15].value == 1 && this.buttonDrightLastValue != gamepad.buttons[15].value){
            newValue = this.getArrayFirstValue(this.trexPanSlider.getValue()) - incrementValue;
            //console.log('new pan ',newValue);
            this.trexPanSlider.setValue(newValue);
        }
        this.buttonDrightLastValue = gamepad.buttons[15].value;




        //A button
        if(gamepad.buttons[0].value == 1 && this.buttonAlastValue != gamepad.buttons[0].value){
            this.cycleEyeColor();
        }
        this.buttonAlastValue = gamepad.buttons[0].value;

        //X button
        if(gamepad.buttons[2].value == 1 && this.button2lastValue != gamepad.buttons[2].value){
            this.trexscream();
        }
        this.button2lastValue = gamepad.buttons[2].value;

        //Y button
        if(gamepad.buttons[3].value == 1 && this.button3lastValue != gamepad.buttons[3].value){
            this.playnextsound();
        }
        this.button3lastValue = gamepad.buttons[3].value;

        var stickChangeThreshold = .02;
        var lefStickX = gamepad.axes[0] - .08;
        lefStickX = Math.round((lefStickX * 500) + 500);
        var change = Math.abs((lefStickX - this.wsPanLast) / this.wsPanLast);
        //console.log('lefStickX : ', change);
        if( change > stickChangeThreshold ){
            this.wsPanLast = lefStickX;
            this.trexPanSlider.setValue(lefStickX);
        }

        var lefStickY = gamepad.axes[1];
        lefStickY = Math.round((lefStickY * 500) + 500);
        var change = Math.abs((lefStickY - this.wsTiltLast) / this.wsTiltLast);
        //console.log('lefStickY : ', change);
        if( change > stickChangeThreshold ){
            this.wsTiltLast = lefStickY;
            this.trexTiltSlider.setValue(lefStickY);
        }


        var rightStickX = gamepad.axes[2];
        this.fieldGamepadLeftRight.setValue(rightStickX);
        var steeringSet = Math.round((rightStickX * 500) + 500);
        //console.log('gamepad steering',steeringSet);
        this.fieldSteeringSetPointText.setValue(steeringSet);

        var fwd = gamepad.buttons[7].value;
        this.fieldGamepadFwd.setValue(fwd);

        var rev = gamepad.buttons[6].value;
        this.fieldGamepadRev.setValue(rev);



        var setThrottle = null;
        if(fwd > 0){
            if(rev > 0){
                setThrottle = 500;
            }else{
                setThrottle = 500 + Math.round(fwd * 500);
            }
        }else{
            setThrottle = 500 - Math.round(rev * 500);
        }

        if(setThrottle !== null){

            if(setThrottle !== this.wsThrottleLast ){
                this.wsThrottleLast = setThrottle;
                this.fieldThrottleText.setValue(setThrottle);
            }
        }

    },

    clearDebugOutput: function() {
        // console.log(message);
        // console.log(this.queryById('debugOutputContainer'));
        var dom = this.queryById('debugOutputContainer').el.dom;
        // console.log(dom);
        dom.innerHTML = "";
    },

    appendDebugOutput: function(message) {
        // console.log(message);
        // console.log(this.queryById('debugOutputContainer'));
        var dom = this.queryById('debugOutputContainer').el.dom;
        // console.log(dom);
        dom.innerHTML += message + "<BR>\r\n";
        // console.log(this.queryById('debugOutputContainerOuter'));
        containerDom = this.queryById('debugOutputContainerOuter').bodyElement.dom;
        containerDom.scrollTop = dom.clientHeight;
    }

});